# Docker Image for compiling and testing the XDBC connector for Postgresql
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# install prerequisites
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        git \
        libc-dev \
        make \
        cmake \
        ca-certificates \
        libssl-dev \
        curl \
        nano \
        gpg  \
        gnupg2  \
        software-properties-common  \
        apt-transport-https  \
        lsb-release  \
        gdb \
        g++ \
    && rm -rf /var/lib/apt/lists/*

# install postgresql server 13
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc| gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list

RUN apt-get update &&  apt-get install -y --no-install-recommends \
                              postgresql-13 \
                              postgresql-server-dev-13

# xdbc prerequisited
RUN apt-get update
RUN apt-get upgrade -qy
RUN apt-get install -qy --no-install-recommends \
        nlohmann-json3-dev \
        clang \
        libboost-all-dev \
        build-essential \
        libspdlog-dev \
        iproute2 \
        libzstd-dev \
        liblzo2-dev \
        liblz4-dev \
        libsnappy-dev \
        libbrotli-dev

RUN git clone https://github.com/lemire/FastPFor.git && cd FastPFor && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    make install

RUN git clone https://github.com/LLNL/fpzip.git && cd fpzip && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    make install

# Copy xdbc files and directories from the host machine to the container and compile submodules
RUN mkdir /pg_xdbc_fdw
COPY submodules /pg_xdbc_fdw/submodules

# Run installation command for xdbc client
WORKDIR /pg_xdbc_fdw/submodules/xdbc-client/
RUN mkdir build && cd build && cmake .. && make -j8 && make install
RUN ldconfig

# Run installation command for xdbc client test
RUN mkdir tests/build && cd tests/build && cmake .. && make -j8
WORKDIR /

# install postgres jdbc and java
RUN echo hi
RUN apt-get update
RUN apt-get upgrade -qy
RUN apt-get install -qy --no-install-recommends \
        openjdk-8-jdk

RUN ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so /usr/lib/libjvm.so
RUN git clone https://github.com/pgspider/jdbc_fdw.git \
    && cd jdbc_fdw \
    && make clean USE_PGXS=1 && make install USE_PGXS=1

# Copy xdbc fdw code
COPY pg_xdbc_fdw.control /pg_xdbc_fdw/
COPY pg_xdbc_fdw--0.1.sql /pg_xdbc_fdw/
COPY Makefile /pg_xdbc_fdw/Makefile
COPY src /pg_xdbc_fdw/src
COPY include /pg_xdbc_fdw/include
RUN mkdir -p /pg_xdbc_fdw/ressources/schemas
COPY ressources/schemas /pg_xdbc_fdw/ressources/schemas
COPY experiments/ /pg_xdbc_fdw/experiments



# Run installation command for the fdw
# first pre generate LLVM IR, as there is no way to give it the needed -std=c++17 flag!!
RUN cd /pg_xdbc_fdw/ && /usr/bin/clang-15 -xc++ -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Xclang -no-opaque-pointers -O2  -I./include -I./submodules/xdbc-client/xdbc -I./submodules/xdbc-server -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -std=c++17 -flto=thin -emit-llvm -c -o src/xdbc_interface.bc src/xdbc_interface.cpp

RUN echo "Installing pg_xdbc_fdw." \
    && cd /pg_xdbc_fdw/ && make USE_PGXS=1 install

# also download postgresql jdbc driver
RUN mkdir /pg_xdbc_fdw/ressources/driver
RUN cd /pg_xdbc_fdw/ressources/driver && curl -O https://jdbc.postgresql.org/download/postgresql-42.7.4.jar

# Copy test files and compile test
COPY test /pg_xdbc_fdw/test
RUN cd /pg_xdbc_fdw/test/xdbc_interface_test/ && make

COPY ./experiments/setup_fdw_lineitem_sf10.sql /pg_xdbc_fdw/experiments/
COPY ./experiments/setup_fdw_iotm.sql /pg_xdbc_fdw/experiments/
COPY ./experiments/setup_fdw_inputeventsm.sql /pg_xdbc_fdw/experiments/
COPY ./experiments/setup_fdw_ss13husallm.sql /pg_xdbc_fdw/experiments/
COPY ./experiments/setup_fdws.sh /pg_xdbc_fdw/experiments/
RUN chmod +x /pg_xdbc_fdw/experiments/setup_fdws.sh

# Set Postgres configuration
USER postgres

RUN    /etc/init.d/postgresql start &&\
    psql --command "ALTER USER postgres WITH PASSWORD '123456';" &&\
    createdb -O postgres db1

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/13/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/13/main/postgresql.conf
EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/13/bin/postgres", "-D", "/var/lib/postgresql/13/main", "-c", "config_file=/etc/postgresql/13/main/postgresql.conf"]