# Docker Image for compiling and testing the XDBC connector for Postgresql
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

# install prerequisites
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        git \
        libc-dev \
        make \
        cmake \
        ca-certificates \
        libssl-dev \
        curl \
        nano \
        gpg  \
        gnupg2  \
        software-properties-common  \
        apt-transport-https  \
        lsb-release  \
        gdb \
        g++ \
    && rm -rf /var/lib/apt/lists/*

# install postgresql server 13
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc| gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list

RUN apt-get update &&  apt-get install -y --no-install-recommends \
                              postgresql-13 \
                              postgresql-server-dev-13

# xdbc prerequisited
RUN apt-get update
RUN apt-get upgrade -qy
RUN apt-get install -qy --no-install-recommends \
        nlohmann-json3-dev \
        clang \
        libboost-all-dev \
        build-essential \
        libspdlog-dev \
        iproute2 \
        libzstd-dev \
        liblzo2-dev \
        liblz4-dev \
        libsnappy-dev \
        libbrotli-dev

RUN git clone https://github.com/lemire/FastPFor.git && cd FastPFor && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    make install

RUN git clone https://github.com/LLNL/fpzip.git && cd fpzip && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    make install

# install postgres dependencies

RUN apt install -qy libpq-dev libpqxx-dev

# install clickhouse depencencies

RUN apt-get install -y libabsl-dev

RUN git clone https://github.com/google/cityhash.git

RUN cd /cityhash && ./configure && make all check CXXFLAGS="-g -O3" && make install

# install clickhouse-lib

RUN git clone https://github.com/ClickHouse/clickhouse-cpp.git

RUN cd /clickhouse-cpp && rm -rf build && mkdir build && cd build && cmake .. -DWITH_SYSTEM_ABSEIL=ON && make -j8 && make install

# copy and install xdbc server
RUN mkdir /xdbc-server

ADD submodules/xdbc-server/* /xdbc-server/
ADD submodules/xdbc-server/Compression /xdbc-server/Compression
ADD submodules/xdbc-server/DataSources /xdbc-server/DataSources
RUN ls /xdbc-server

RUN rm -rf  /xdbc-server/CMakeCache.txt
RUN rm -rf /xdbc-server/build && mkdir /xdbc-server/build && cd /xdbc-server/build && cmake .. -D CMAKE_BUILD_TYPE=Release && make -j8

# add data import scripts
COPY experiments/ /experiments/

# Set Postgres configuration
USER postgres

RUN    /etc/init.d/postgresql start &&\
    psql --command "ALTER USER postgres WITH PASSWORD '123456';" &&\
    createdb -O postgres db1

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/13/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/13/main/postgresql.conf
EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/13/bin/postgres", "-D", "/var/lib/postgresql/13/main", "-c", "config_file=/etc/postgresql/13/main/postgresql.conf"]